# Stage 1: build base image with prequisite packages
FROM arm32v7/ubuntu:xenial
LABEL maintainer="tuanlm@greenglobal.vn"

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# Install necessary packages for the installer
RUN apt-get update -y && \
    apt-get dist-upgrade -y && \
    apt-get autoremove -y
RUN apt-get install update-manager-core -y

RUN apt-get install --fix-missing -y \
    apt-utils lsb-release build-essential apt-transport-https \
    usbutils unzip coreutils curl git sed sudo tar udev wget \
    automake cmake make libusb-1.0-0-dev libatlas-base-dev \
    libopenblas-dev libprotobuf-dev libleveldb-dev libsnappy-dev \
    libopencv-dev libhdf5-serial-dev libgflags-dev libgoogle-glog-dev \
    liblmdb-dev libxslt-dev libxml2-dev libgraphviz-dev protobuf-compiler \
    byacc swig3.0 graphviz gfortran python-dev python-numpy python-pip python3 \
    python3-dev python3-numpy python3-scipy python3-yaml python3-nose python3-tk python3-pip

# Run the installer
COPY pip.conf /etc/pip.conf
# RUN pip install --upgrade pip
# RUN pip install virtualenv virtualenv-tools
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python2 get-pip.py && \
    python3 get-pip.py

RUN pip3 install -U "Cython>=0.23.4,<=0.26"
RUN pip3 install "pygraphviz>=1.3.1" "graphviz>=0.4.10,<=0.8" "Enum34>=1.1.6" "networkx>=2.1,<=2.1"

# Do clean jobs
RUN sudo apt-get clean && sudo apt-get autoremove


